### ISSUE TITLE
Script isn't working

### ISSUE THREAD

**Issue by matmuilwijk** [uzegonemad/plexbgartwork#1]
Using Chrome, latest Linux-release, and the script doesn't show any extra artwork.

I did change the script so it would include my own reverse proxy, but before the changes it didn't show either.

I do however see a change in background that I didn't notice before, the color gray changes a bit. But, still no artwork!

**Comment by matmuilwijk** [comment]
NVM, gave plex a reboot, and this fixed it! #closed

**Comment by uzegonemad** [comment]
Plex probably needed a hard refresh. FYI I updated the readme to include instructions for Stylish in case you want to use it instead.

Thanks!
